2018-01-09 11:09:44.691 [info] <0.193.0> Node database directory at /var/lib/rabbitmq/mnesia/rabbit@10.244.2.14 is empty. Assuming we need to join an existing cluster or initialise from scratch...
2018-01-09 11:09:44.691 [info] <0.193.0> Configured peer discovery backend: rabbit_peer_discovery_k8s
2018-01-09 11:09:44.691 [info] <0.193.0> Will try to lock with peer discovery backend rabbit_peer_discovery_k8s
2018-01-09 11:09:44.691 [info] <0.193.0> Peer discovery backend rabbit_peer_discovery_k8s does not support registration, skipping randomized startup delay.
2018-01-09 11:09:44.710 [info] <0.193.0> Failed to get nodes from k8s - 403
2018-01-09 11:09:44.711 [error] <0.192.0> CRASH REPORT Process <0.192.0> with 0 neighbours exited with reason: no case clause matching {error,"403"} in rabbit_mnesia:init_from_config/0 line 163 in application_master:init/4 line 134
2018-01-09 11:09:44.711 [info] <0.33.0> Application rabbit exited with reason: no case clause matching {error,"403"} in rabbit_mnesia:init_from_config/0 line 163
Kernel pid terminated (application_controller) ({application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,"403"}},[{rabbit_mnesia,init_from_config,0,[{file
{"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,\"403\"}},[{rabbit_mnesia,init_from_config,0,[{file,\"src/rabbit_mnesia.erl\"},{line,163}]},{rabbit_mnesia,init_with_lock,3,[{file,\"src/rabbit_mnesia.erl\"},{line,143}]},{rabbit_mnesia,init,0,[{file,\"src/rabbit_mnesia.erl\"},{line,111}]},{rabbit_boot_steps,'-run_step/2-lc$^1/1-1-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,49}]},{rabbit_boot_steps,run_step,2,[{file,\"src/rabbit_boot_steps.erl\"},{line,49}]},{rabbit_boot_steps,'-run_boot_steps/1-lc$^0/1-0-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,26}]},{rabbit_boot_steps,run_boot_steps,1,[{file,\"src/rabbit_boot_steps.erl\"},{line,26}]},{rabbit,start,2,[{file,\"src/rabbit.erl\"},{line,802}]}]}}}}}"}

Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done



2018-02-03 17:50:15.812 [info] <0.193.0> Node database directory at /var/lib/rabbitmq/mnesia/rabbit@10.244.2.132 is empty. Assuming we need to join an existing cluster or initialise from scratch...
2018-02-03 17:50:15.812 [info] <0.193.0> Configured peer discovery backend: rabbit_peer_discovery_k8s
2018-02-03 17:50:15.813 [info] <0.193.0> Will try to lock with peer discovery backend rabbit_peer_discovery_k8s
2018-02-03 17:50:15.813 [info] <0.193.0> Peer discovery backend rabbit_peer_discovery_k8s does not support registration, skipping randomized startup delay.
2018-02-03 17:50:15.870 [info] <0.193.0> Failed to get nodes from k8s - {failed_connect,[{to_address,{"kubernetes.default.svc.cluster.local",6443}},
                 {inet,[inet],econnrefused}]}
2018-02-03 17:50:15.870 [error] <0.192.0> CRASH REPORT Process <0.192.0> with 0 neighbours exited with reason: no case clause matching {error,"{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",6443}},\n                 {inet,[inet],econnrefused}]}"} in rabbit_mnesia:init_from_config/0 line 163 in application_master:init/4 line 134
2018-02-03 17:50:15.871 [info] <0.33.0> Application rabbit exited with reason: no case clause matching {error,"{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",6443}},\n                 {inet,[inet],econnrefused}]}"} in rabbit_mnesia:init_from_config/0 line 163
Kernel pid terminated (application_controller) ({application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,"{failed_connect,[{to_address,{\"kubernetes.defau

{"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,\"{failed_connect,[{to_address,{\\"kubernetes.default.svc.cluster.local\\",6443}},\n                 {inet,[inet],econnrefused}]}\"}},[{rabbit_mnesia,init_from_config,0,[{file,\"src/rabbit_mnesia.erl\"},{line,163}]},{rabbit_mnesia,init_with_lock,3,[{file,\"src/rabbit_mnesia.erl\"},{line,143}]},{rabbit_mnesia,init,0,[{file,\"src/rabbit_mnesia.erl\"},{line,111}]},{rabbit_boot_steps,'-run_step/2-lc$^1/1-1-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,49}]},{rabbit_boot_steps,run_step,2,[{file,\"src/rabbit_boot_steps.erl\"},{line,49}]},{rabbit_boot_steps,'-run_boot_steps/1-lc$^0/1-0-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,26}]},{rabbit_boot_steps,run_boot_steps,1,[{file,\"src/rabbit_boot_steps.erl\"},{line,26}]},{rabbit,start,2,[{file,\"src/rabbit.erl\"},{line,792}]}]}}}}}"}
Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
